version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/openjdk:11-jdk
    working_directory: /tmp/workspace
    steps:
      - checkout
      - run: mkdir -p /tmp/workspace
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "pom.xml" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: mvn clean install -DskipTests
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies-{{ checksum "pom.xml" }}
      - persist_to_workspace:
          root: /tmp/workspace
          paths: .
  docker-image-and-publish:
    machine: true
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: ls -a /tmp/workspace
      - run:
          name: Create Docker image and push to ECR
          command: aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 598715871319.dkr.ecr.us-east-2.amazonaws.com/ticketingapp && docker build -t ticketingapp /tmp/workspace && docker tag ticketingapp:latest 2598715871319.dkr.ecr.us-east-2.amazonaws.com/ticketingapp/ticketingapp:latest && docker push 598715871319.dkr.ecr.us-east-2.amazonaws.com/ticketingapp/ticketingapp:latest
  deploy-job:
    docker:
      #specify the version you desire here
      - image: circleci/node:10.0.0
    steps:
      - run:
          name: Execute Deployment Script
          command: |
            ssh -o "StrictHostKeyChecking=no" ec2-3-134-104-164.us-east-2.compute.amazonaws.com <<'ENDSSH'
            /bin/bash bin/deploy_images.sh
            docker ps
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - docker-image-and-publish:
          requires:
            - build
      - deploy-job:
          requires:
            - docker-image-and-publish
